from datetime import datetime
from decimal import Decimal
from src.articles.domain.article import Article
from src.articles.application.ports.article_repository import ArticleRepository

# create a new article
class CreateArticleUseCase:
  
    def __init__(self, repository: ArticleRepository):
        self.repository = repository

    def execute(self, reference: str, name: str, description: str, price_without_tax: Decimal, tax: Decimal) -> Article:
        
        # bbdd will asign id and date will be generated by domain
        article = Article(id=None, reference=reference, name=name, description=description, price_without_tax=price_without_tax, tax=tax, created_at=datetime.now())

        return self.repository.save(article)